spring:
  application:
    name: portfolio
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
  web:
    error:
      include-message: always
      include-binding-errors: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=200,expireAfterWrite=2h


# cloudinary://<api_key>:<api_secret>@<cloud_name>, from the Cloudinary dashboard
cloudinary:
  url: ${CLOUDINARY_URL:}

